name: build-and-deploy-frontend
on: workflow_dispatch
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      container: google/cloud-sdk:latest
      steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-and-deploy
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          apt update
          apt install nodejs npm -y
          echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > key.json
          gcloud auth activate-service-account --key-file=key.json
          make deploy-frontend
